server:
  port: 8080

spring:
  main:
    banner-mode: off

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/auth_attempt
    username: root
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        format_sql: true

aes.encryption.key: this-is-test-key